### ISSUE TITLE
Add retirement age slider to both the birth date page and keep it on the results page

### ISSUE THREAD

**Issue by annemeeker** [codeforboston/windfall-elimination#109]
from Results page:
![image](https://user-images.githubusercontent.com/283343/68442152-224aa800-019e-11ea-96d3-05c29e4dc3fa.png)

**Comment by thadk** [comment]
I guess the other minor question with this design is how do we explain full retirement age on the first page?

**Comment by thadk** [comment]
The other thing is that the values of the beginning and end sliders should always match. The text and calculated value at the top of the last page changes to what is shown above.

**Comment by thadk** [comment]
This code (roughly) should get the Full Retirement Age for the birth year given:
`benefitReductionTable.find(d => d.year ===dayjs(birthDatePicked).year()).NormalRetirementAge`

![image](https://user-images.githubusercontent.com/283343/68995318-4a02d580-085a-11ea-8001-87a628275df3.png)

**Comment by thadk** [comment]
This has been finished: we decided not to add the slider to the front page because we don't really need anything except the birth date until the end: we want them to focus on full retirement age by default.
