### ISSUE TITLE
Create an FAQ page

### ISSUE THREAD

**Issue by emeegoda** [codeforboston/windfall-elimination#122]
(@annemeeker  to write answers)
How do I fight Windfall Elimination Provision?
Social security told me I had an overpayment. What do I do?
“How do I calculate spousal benefits?
“How do I know how much my pension is?”

**Comment by annemeeker** [comment]
![Screen Shot 2019-12-08 at 9 39 05 AM](https://user-images.githubusercontent.com/50156013/70391034-9c896a80-199e-11ea-968a-fe3c98e0c769.png)

**Comment by thadk** [comment]
![image](https://user-images.githubusercontent.com/283343/94048036-e8c46080-fda0-11ea-907b-2a3f295a2976.png)
<img width="477" alt="image" src="https://user-images.githubusercontent.com/283343/94049006-52913a00-fda2-11ea-8060-5fdbfaf2a077.png">
