### ISSUE TITLE
Clarify to people entering earnings record manually to type in earnings record after 18

### ISSUE THREAD

**Issue by emeegoda** [codeforboston/windfall-elimination#124]
(we can clarify for everyone but people entering this information manually need this nudge the most)

**Comment by thadk** [comment]
@supjohn Do you think that years of income before you are 18 can count into your average indexed monthly earnings (AIME)?

**Comment by thadk** [comment]
If not, we might alter the text like suggested. If they are, lets add the extra fields or a button to add more fields.
Regardless, lets create boxes for every year until they are 70 years from Date of Birth.

**Comment by emeegoda** [comment]
This is a question for Anne. I can’t remember if Anne said that years
before 18 never count or are unlikely to ever count.
