### ISSUE TITLE
Support retirement planning: show earnings record up to 2 years beyond today

### ISSUE THREAD

**Issue by emeegoda** [codeforboston/windfall-elimination#127]
# Future Projections

Here were the three things that each needed some kind of tactic for their projection:
• A person's earnings into the future
• Avg & Maximum US-wide SSA Wages tables
• SSA Bendpoints (largely based on cost of living adjustments (COLA) multiples?)

## Earnings:
**Manual projection:** the user inputs each future year manually. No extrapolation calculations on our end.
New Parameters: None, but the earnings record must be changed to allow entry for future years.
Pros: No calculations on our end; we’re not responsible for any mistakes
Cons: Is only as accurate as the user’s predictions

**Tabular Extrapolation:** we use the values we got from from the trustee report, which specify predicted increases in average wages, to extrapolate the user’s future wages from existing records.
New Parameters: the year from which to extrapolate future data - this will commonly be the most recent year in which the user has earnings, but may differ in the case that the user has years of unusual earnings not suitable to extract from.
Pros: Uses well-researched values provided by an unaffiliated organization; puts very little burden on the user
Cons: Computation intensive; puts very little burden on the user – and thus, makes us seem most responsible for inaccuracies.

**Manual Extrapolation:** a mix of Manual Projection and Tabular Extrapolation: uses user defined percentages to extrapolate future values from existing records.
New Parameters: the year from which to extrapolate future data; a table of percentage values
Pros: Gives control to the user while taking the burden of calculation away from them
Cons: As computation intensive as Tabular Extrapolation; is only as accurate as the user’s predictions; most likely to utterly confuse an ill-qualified user

**Static Extrapolation:** like tabular extrapolation, but uses a single, static value to calculate Wage Growth. Note: this number may be selected from a set of options, or we may allow manual entry.
New Parameters: the year from which to extrapolate user data; a percentage value to use for yearly increase
Pros: Least susceptible to “noise” and attempts to be overly clever in predictions; easy to understand
Cons: May sacrifice too much accuracy for simplicity; if the percentage may be manually entered, is only as accurate as the user’s predictions.

## Average Wages & Maximum Earnings:
**Tabular Extrapolation:** use our stored wage growth values to extrapolate future years of average wages from the last known year.
New Parameters: None
Pros: Uses well-researched values provided by an unaffiliated organization; puts very little burden on the user
Cons: Computation intensive; puts very little burden on the user – and thus, makes us seem most responsible for inaccuracies.

**Static Extrapolation:** like tabular extrapolation, but uses a single, static value to calculate Wage Growth. Note: this number may be selected from a set of options, or we may allow manual entry.
New Parameters: a percentage value to use for yearly increase
Pros: Least susceptible to “noise” and attempts to be overly clever in predictions; easy to understand
Cons: May sacrifice too much accuracy for simplicity; if the percentage may be manually entered, is only as accurate as the user’s predictions.

**Manual Extrapolation (?!):** have the user enter percentages by which they believe average wages will increase for each year.
New Parameters: an entire table of percentages
Pros: ~1% chance the user knows something very specific that the trustee report doesn’t account for
Cons: 99% chance it gives users a new way to make horrible mistakes

## Bendpoints and COLA

Further investigation needed. See tables below.

(the above is based on a Word Document by @supjohn)

# Other Details to incorporate above:

https://cfb-public.slack.com/archives/CG08M4KN3/p1575418598247600

How SSA Detailed Calculator app, called AnyPIA helps users do projections, in screenshots: https://cfb-public.slack.com/archives/CG08M4KN3/p1562009569050800?thread_ts=1562003269.042200&cid=CG08M4KN3

#### Whiteboard discussion of above projection tactics

![image](https://user-images.githubusercontent.com/283343/70109670-9e5bd280-161a-11ea-9abb-d8bbf3e1ebe7.png)

https://cfb-public.slack.com/archives/CG08M4KN3/p1563925431005000
![image](https://user-images.githubusercontent.com/283343/70105900-3a341100-1610-11ea-9772-73a947807804.png)
Page 16 from Trustees report 2019.2

![image](https://user-images.githubusercontent.com/283343/70109820-19bd8400-161b-11ea-8b32-381dead46fb4.png)
Page 99 from Trustees report 2019.2

https://cfb-public.slack.com/archives/CG08M4KN3/p1563926600006400
![image](https://user-images.githubusercontent.com/283343/70105841-035dfb00-1610-11ea-97d7-2198de9b8667.png)

**Comment by alexjcode** [comment]
Moving forward with the future earnings projections.

Whiteboards (in red at top):
https://cfb-public.slack.com/archives/CG08M4KN3/p1570585257136400
https://cfb-public.slack.com/archives/CG08M4KN3/p1570585420137100

Here were the three things that each needed some kind of tactic for their projection:
A person's earnings into the future
Avg & Maximum US-wide SSA Wages tables
SSA Bendpoints (largely based on cost of living adjustments multiples?)

**Comment by alexjcode** [comment]
https://cfb-public.slack.com/files/UG3H04LE8/FP6JH33FX/image_from_ios.jpg
https://cfb-public.slack.com/files/UG3H04LE8/FP8QGK2UW/image_from_ios.jpg
https://cfb-public.slack.com/files/UG3H04LE8/FP6JHJR0D/image_from_ios.jpg
https://cfb-public.slack.com/files/UG3H04LE8/FNV49CS9Z/image_from_ios.jpg

**Comment by alexjcode** [comment]
## Projection options

Earnings:
Manual projection:
the user inputs each future year manually. No extrapolation calculations on our end.New Parameters: None, but the earnings record must be changed to allow entry for future years.Pros: No calculations on our end; we’re not responsible for any mistakesCons: Is only as accurate as the user’s predictionsTabular Extrapolation: we use the values we got from from the trustee report, which specify predicted increases in average wages, to extrapolate the user’s future wages from existing records.New Parameters: the year from which to extrapolate future data - this will commonly be the most recent year in which the user has earnings, but may differ in the case that the user has years of unusual earnings not suitable to extract from.Pros: Uses well-researched values provided by an unaffiliated organization; puts very little burden on the userCons: Computation intensive; puts very little burden on the user – and thus, makes us seem most responsible for inaccuracies.Manual Extrapolation: a mix of Manual Projection and Tabular Extrapolation: uses user defined percentages to extrapolate future values from existing records.New Parameters: the year from which to extrapolate future data; a table of percentage valuesPros: Gives control to the user while taking the burden of calculation away from themCons: As computation intensive as Tabular Extrapolation; is only as accurate as the user’s predictions; most likely to utterly confuse an ill-qualified userStatic Extrapolation: like tabular extrapolation, but uses a single, static value to calculate Wage Growth. Note: this number may be selected from a set of options, or we may allow manual entry.New Parameters: the year from which to extrapolate user data; a percentage value to use for yearly increasePros: Least susceptible to “noise” and attempts to be overly clever in predictions; easy to understandCons: May sacrifice too much accuracy for simplicity; if the percentage may be manually entered, is only as accurate as the user’s predictions.Average Wages and Maximum Earnings:Tabular Extrapolation: use our stored wage growth values to extrapolate future years of average wages from the last known year.
New Parameters: NonePros: Uses well-researched values provided by an unaffiliated organization; puts very little burden on the userCons: Computation intensive; puts very little burden on the user – and thus, makes us seem most responsible for inaccuracies.Static Extrapolation: like tabular extrapolation, but uses a single, static value to calculate Wage Growth. Note: this number may be selected from a set of options, or we may allow manual entry.New Parameters: a percentage value to use for yearly increasePros: Least susceptible to “noise” and attempts to be overly clever in predictions; easy to understandCons: May sacrifice too much accuracy for simplicity; if the percentage may be manually entered, is only as accurate as the user’s predictions.Manual Extrapolation (?!): have the user enter percentages by which they believe average wages will increase for each year.New Parameters: an entire table of percentagesPros: ~1% chance the user knows something very specific that the trustee report doesn’t account forCons: 99% chance it gives users a new way to make horrible mistakes

**Comment by alexjcode** [comment]
Ok, I looked through this. It seems like Tabular Ext and Static Ext are the best options. As an alternative (Manual Projection), there could be 2 sliders at the end where the user can adjust the future earnings for just those years. Do we have a strategy to decide what calculation method to go with?

**Comment by alexjcode** [comment]
## Relevant Values
- AvgWageIndex (actual values up to 2018) (predicted up to 2033)
- **MaximumEarningsCreditable (actual values up to 2020)**
- Bendpoints (actual values up to 2020) (predicted up to 2040)
- [**COLA (actual values up to 2019) (predicted up to 2040)**](https://docs.google.com/spreadsheets/d/1FlkSS1JOSV5yA3qN1rnek9N5zPVoSu-H/edit#gid=111928466)
- User's Future Earnings (user input)

Looks like **Max Earnings** and **COLA** are the main values to start with

### COLA data
https://observablehq.com/@thadk/windfall-awareness-notebook-prototype
https://www.ssa.gov/OACT/COLA/colaseries.html
https://www.ssa.gov/OACT/COLA/latestCOLA.html
https://www.ssa.gov/OACT/COLA/bendpoints.html
<img src="https://user-images.githubusercontent.com/283343/70105900-3a341100-1610-11ea-9772-73a947807804.png">

### Max Earnings data
https://github.com/bslabs/anypiamac/blob/master/oactobjs/piadataproj/awincnf.cpp
https://github.com/bslabs/anypiamac/blob/master/oactobjs/piadataproj/biprojnf.cpp

**Comment by alexjcode** [comment]
https://observablehq.com/@thadk/windfall-awareness-notebook-prototype
<img width="714" alt="Screen Shot 2020-01-07 at 9 32 16 PM" src="https://user-images.githubusercontent.com/47488382/71945640-5ee25200-3195-11ea-81c4-4733ad2999c0.png">
<img width="658" alt="Screen Shot 2020-01-07 at 9 32 36 PM" src="https://user-images.githubusercontent.com/47488382/71945656-69045080-3195-11ea-8715-d800036c9ee8.png">
<img width="709" alt="Screen Shot 2020-01-07 at 9 32 49 PM" src="https://user-images.githubusercontent.com/47488382/71945660-6c97d780-3195-11ea-8288-752e424ac140.png">

**Comment by alexjcode** [comment]
## COLA Predictions
https://docs.google.com/spreadsheets/d/1FlkSS1JOSV5yA3qN1rnek9N5zPVoSu-H/edit#gid=111928466

<img width="813" alt="Screen Shot 2020-01-14 at 6 17 43 PM" src="https://user-images.githubusercontent.com/47488382/72391058-352bac80-36fa-11ea-9a46-1fc5cde987c7.png">

**Comment by alexjcode** [comment]
Trustees report
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf

**Comment by alexjcode** [comment]
The projected average annual growth rates in the average covered wage from 2028 to 2093 are 5.04, 3.81, and 2.60 percent for the low-cost, intermediate, and high-cost assumptions, respectively.
The estimated annual rate of change in the average covered wage is 2.98 percent for 2018.
For the intermediate assumptions, as the economy continues to recover, the annual rate of change in the average covered wage averages 4.23 percent from 2018 to 2028.
Thereafter, the average annual rate of change in the average covered wage is 3.81 percent.
(page 111 of the trustees report)

**Comment by alexjcode** [comment]
Found the low and high cost assumptions!
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=16
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=111
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=112
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=113
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=123
<img width="518" alt="Screen Shot 2020-01-21 at 8 18 05 PM" src="https://user-images.githubusercontent.com/47488382/72857507-d0d59380-3c8b-11ea-80b7-9b189138c8fc.png">
<img width="588" alt="Screen Shot 2020-01-21 at 8 17 53 PM" src="https://user-images.githubusercontent.com/47488382/72857551-f6629d00-3c8b-11ea-8505-ece65906e42f.png">

**Comment by alexjcode** [comment]
Bendpoints predictions
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=127
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=128

**Comment by alexjcode** [comment]
## Predictions

✅ Bendpoints => Directly predicted
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=127
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=128

✅ Benefit Reduction => Stays the same

(Needs to be verified)
Substantial Earnings => Calculated using Δ Average Annual Wage in Covered Employment
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=112

✅ CPI-W => COLA
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=112

(Needs to be verified)
Max Wages Taxable => Calculated using Δ Average Annual Wage in Covered Employment
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=112

✅ Average Wage Index => Directly predicted
https://www.ssa.gov/OACT/TR/2019/tr2019.pdf#page=123

**Comment by alexjcode** [comment]
Formulas
https://docs.google.com/document/d/13cmLTbSPMelH3Trwn97XvbacHwunfRQp0ScHgDng_-c/edit#
Source code
https://www.ssa.gov/OACT/anypia/source.html

https://github.com/alexjcode/ssa-source-code

**Comment by thadk** [comment]
https://github.com/alexjcode/ssa-source-code
