### ISSUE TITLE
Consider including sample XML so users can test out the flow with actual data

### ISSUE THREAD

**Issue by morrisond7** [codeforboston/windfall-elimination#128]
- [x] Specify what the user interface would look like
- [x] Or figure out a flow for users who don't want to use their own data can use `Sample-20.xml`

**Comment by alexjcode** [comment]
Would this include a sample DOB, or is the data is adjusted based on user input?

**Comment by morrisond7** [comment]
There's an age in the file I've been using (security.xml)

Also, I've added two possible implementations in the Figma, though the Home screen appears to be an old one. Do we have a copy of the current screen living somewhere there or elsewhere?

**Comment by morrisond7** [comment]
[security.txt](https://github.com/codeforboston/windfall-elimination/files/3919489/security.txt)
Reconvert to XML
