### ISSUE TITLE
Update the wep table cache for 2020

### ISSUE THREAD

**Issue by thadk** [codeforboston/windfall-elimination#134]
I made a first pass to the spreadsheet to update the new values that were available at Christmas. 
Let's wait for the 2020 WEP substantial earnings threshold release in January if it comes out before we want to go live. 

Then let's update the `wep-table` and `wep-cache`. You can pregenerate much of the cache using [observable](https://observablehq.com/@thadk/windfall-awareness-notebook-prototype) but it may or may not have the actuarial table yet.

From the Observable:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/283343/72013944-ec24b580-322c-11ea-9036-7053d84d4d3a.png">

**Comment by alexjcode** [comment]
https://www.ssa.gov/OACT/COLA/bendpoints.html

**Comment by thadk** [comment]
The official [PDF for Windfall](https://www.ssa.gov/pubs/EN-05-10045.pdf) is now updated for 2020:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/283343/72013782-8fc19600-322c-11ea-8b20-ea1c1d30ed53.png">
I added the new value to the `SubstantialEarningsClean` spreadsheet.

We may want to link to this table in the FAQ as well: https://www.ssa.gov/planners/retire/wep-chart.html
