### ISSUE TITLE
Use months instead of years for retirement date calculation

### ISSUE THREAD

**Issue by paavanb** [codeforboston/windfall-elimination#145]
The `fullRetirementAge` returned from the API is a fractional number, but `dayjs` cannot add fractional years.

`dayjs(new Date()).add(0.5, 'year').toDate()` will return the current date, so we need to store full retirement age in months to be able to add it to the birth date correctly.

https://github.com/codeforboston/windfall-elimination/blob/4a3bf3aa85539c9cd37b8cde1f94397fc709a5d5/src/pages/prescreen-1a.tsx#L82

**Comment by thadk** [comment]
Closed with a6b02ee92323636789a31d3390dd08f45ef49a90 and #147
