### ISSUE TITLE
Preliminary mobile design

### ISSUE THREAD

**Issue by WheresHJ** [codeforboston/windfall-elimination#155]
A first pass at adapting the current design for mobile. The major features are moving the side menu into a drop-down, truncating some of the button names, and minor adjustments to typography size.

---
## Menu closed
![windfall_Step 2a](https://user-images.githubusercontent.com/642810/72858207-02e7f500-3c8e-11ea-8475-3bdf7bc329bd.png)

---
## Menu open
![windfall_Step 2b](https://user-images.githubusercontent.com/642810/72858212-054a4f00-3c8e-11ea-9a39-556945d33c48.png)

**Comment by WheresHJ** [comment]
Sketch file for reference attached.

[windfall.sketch.zip](https://github.com/codeforboston/windfall-elimination/files/4097978/windfall.sketch.zip)

**Comment by thadk** [comment]
Added them to the [main figma](https://cfb-public.slack.com/archives/CG08M4KN3/p1573609699158200)! Thanks again.

**Comment by thadk** [comment]
Added them to the [main figma](https://cfb-public.slack.com/archives/CG08M4KN3/p1573609699158200). 

Thanks again, Harlan. 
👋 @misspran welcome to this issue if you've any interest now that this may be adopted at scale by Mass Retirees, huzzah.

**Comment by nadermokhtar** [comment]
Hi, I am taking this on.

**Comment by thadk** [comment]
This is mostly finished now, but we just need to shrink the font size on the glossary to match the mockup I think.
