### ISSUE TITLE
Earnings -> YSE

### ISSUE THREAD

**Issue by nvanwitt** [codeforboston/windfall-elimination#16]
Calculate Years of Substantial Earnings (YSE) from user-inputted earnings records.

If code works, localize to the correct demo screen page; move to Tests board -> getAIME() Test

**Comment by thadk** [comment]
I'd like us to experiment with https://observablehq.com/@mbostock/embedded-notebook technique like below to include from Observable Notebook ES6 module first so we don't need to duplicate the code or maybe even the widgets.

```
import {Runtime, Inspector} from "https://cdn.jsdelivr.net/npm/@observablehq/runtime@4/dist/runtime.js";
import define from "https://api.observablehq.com/@d3/bar-chart.js?v=3";

new Runtime().module(define, name => {
  if (name === "chart") {
    return new Inspector(document.body);
  }
});
```

**Comment by nvanwitt** [comment]
@thadk On Tuesday, we discussed moving away from Observable for production. The general consensus was creating a self-contained app with no third party dependencies. 
That being said, you weren’t present so we probably missed out on valid counter-points. We should definitely revisit this topic when we meet again.
