### ISSUE TITLE
Add human-readable Emotion class names

### ISSUE THREAD

**Issue by rmorantes** [codeforboston/windfall-elimination#177]
Emotion is currently generating class names like "css-mv5f6b e13vrpb91". Something more like "My-Component-1s1pjfp-1" would make for a better DX.

`babel-plugin-emotion` seems like a good place to start: "[Feature] Contextual Class Names -  Generated class names include the name of the variable or component they were defined in."

https://emotion.sh/docs/babel-plugin-emotion

**Comment by thadk** [comment]
I realized that this is actually already turned on for `localhost`:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/283343/75403412-ac498880-58d5-11ea-8918-35376b08cf3f.png">

In the docs you link:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/283343/75631055-bad9bd80-5bbd-11ea-883d-4e6dc6d5026c.png">

**Comment by thadk** [comment]
Can someone try to set the `autoLabel` to true in the correct part of our `.babelrc` and make a PR so we can see if this fixes it?
