### ISSUE TITLE
When you delete date picker contents, app crashes

### ISSUE THREAD

**Issue by thadk** [codeforboston/windfall-elimination#181]
With the latest state/context management, we noticed when the date picker gets emptied using the delete key, the app crashes and goes white, at least on Firefox.

![crash](https://user-images.githubusercontent.com/283343/78737144-d5b9f300-791c-11ea-8da9-265b0b3a10f7.gif)

**Comment by Kevin1192** [comment]
After adding a null value check inside the if statement, the page will no longer crash. It will, however, stay at the previously selected date when the user deletes the date.

![github bug fix](https://user-images.githubusercontent.com/50506809/78830447-f8e4b100-79b5-11ea-8f3d-597fb5328c32.gif)


![github bug fix2](https://user-images.githubusercontent.com/50506809/78831304-6513e480-79b7-11ea-83f4-60e6d2df0c04.gif)



This is the first time I worked on projects with others. I'm trying to figure out how to perform a pull request.

**Comment by paavanb** [comment]
Good find! It looks like when the value is cleared, we need to `setBirthDate(null)` and `setRetireDate(null)`. This should be possible if we update the `UserStateActions` interface to accept `null` as an argument.
