### ISSUE TITLE
Where to place AnyPIA Assumptions in the Windfall app

### ISSUE THREAD

**Issue by alexjcode** [codeforboston/windfall-elimination#190]
### Show earnings record for retirees retiring up to 2 years beyond today
See full issue with policy research: https://github.com/codeforboston/windfall-elimination/issues/127

### Average Wage Increase (AWI)
AWI is the only assumption that impacts the user's future wage projections, so it should go on page 1D. We will create this new page after Page 1C / "Step 3: Employment"
<img width="347" alt="Screen Shot 2020-05-19 at 10 49 52 PM" src="https://user-images.githubusercontent.com/47488382/82399465-314ec480-9a23-11ea-8c00-e05fbfe95430.png">
this is like (Page 1D):
<img width="125" src="https://user-images.githubusercontent.com/47488382/82495183-ba640b00-9ab8-11ea-9d96-abf7a09d7ede.png">

### Benefit Increase (BI)
BI Assumptions are tied to the overall economic and SSA policy status of the time, so **these can go on the final "results" page**, since they do have an impact on pensions, just not wages.
<img width="245" alt="Screen Shot 2020-05-19 at 10 51 12 PM" src="https://user-images.githubusercontent.com/47488382/82399504-488db200-9a23-11ea-9f56-bf98f6da4eb2.png">

### Projected Wage Base
<img width="151" alt="Screen Shot 2020-05-19 at 10 51 17 PM" src="https://user-images.githubusercontent.com/47488382/82399531-55120a80-9a23-11ea-8de9-f30ace9766e7.png">
<a href="https://www.ssa.gov/OACT/anypia/download/anypia32.pdf#page=57">https://www.ssa.gov/OACT/anypia/download/anypia32.pdf#page=57</a>
<img width="814" alt="Screen Shot 2020-05-20 at 4 39 25 PM" src="https://user-images.githubusercontent.com/47488382/82495039-825cc800-9ab8-11ea-95b1-57d6ad880c15.png">
This seems like an advanced feature, might be useful in some cases though

**Comment by thadk** [comment]
From http://thadk.net/anypiamac-docs/html/General/structure.html
<img width="250" alt="image" src="https://user-images.githubusercontent.com/283343/92542600-2d83bf80-f217-11ea-8c16-225a54f54386.png">

For `Sample 25.pia` when we changed both to 2019 Trustees Report Alternative I (2020.1 version).

http://thadk.net/anypiamac-docs/html/Forms/ben_inc_sets.html
http://thadk.net/anypiamac-docs/html/Forms/avg_wage_sets.html

The line 40 changed like this:
a) `402017551`
to
b) `402020111`

c) And when we changed it to other and put 1 in the box:
```
402020771
41 0.0 0.0 0.0
551
56  0.00  0.00  0.00  0.00
601
```
