### ISSUE TITLE
Create a toggle radio button for which calculator to use

### ISSUE THREAD

**Issue by thadk** [codeforboston/windfall-elimination#205]
Build off of the branch in #196 and add a React checkbox [along the lines of the other ones](https://github.com/codeforboston/windfall-elimination/blob/b2d357c0a97c22f0fd75d5a037400e6ae512e6d5/src/pages/prescreen-1b.tsx#L213-L237). The checkbox should toggle between our two calculators functions:
- `piaUserCal` (newly added C++-based AnyPIA.exe app) and 
- `userCalc` (our Congressional Research Service informed algorithm)

Each outputs a similar `UserProfile` that can work on the final results page.

https://github.com/codeforboston/windfall-elimination/blob/b2d357c0a97c22f0fd75d5a037400e6ae512e6d5/src/pages/screen-2.tsx#L127-L137

The `piaUserCal` `UserProfile` is the [only one that can work for retiree users who are younger than about 61](https://github.com/codeforboston/windfall-elimination/blob/b2d357c0a97c22f0fd75d5a037400e6ae512e6d5/src/pages/prescreen-1a.tsx#L137-L146) so is important for users planning their retirement. 

*Question text: Which calculator would you like to see results of?*
LabelText 1: Official Social Security Calculator (AnyPIA)
LabelText 2: Our Calculator

You will need to add a new React Hook to `user-state-context.tsx` to hold the new boolean state like `haveEarnings` and a new setter function like `setHaveEarnings` to `user-state-actions-context.tsx`

**Comment by dmeegan** [comment]
Hey all, I am working on this issue. Hope to have something working shortly.
