### ISSUE TITLE
When you toggle the calculator, the age shown resets to Full Retirement Age

### ISSUE THREAD

**Issue by thadk** [codeforboston/windfall-elimination#208]
This might be a good one for @dmeegan following up on #205 / #207

Seems might be mostly happening in one direction but not as much the other:
![toggledate](https://user-images.githubusercontent.com/283343/91936215-7094de80-ecbd-11ea-8ee7-be4ed45dd3bd.gif)
![toggledate2](https://user-images.githubusercontent.com/283343/91936225-738fcf00-ecbd-11ea-8c13-1e885526e6f6.gif)

**Comment by dmeegan** [comment]
I spent some time looking at this yesterday. I noticed that the console log is showing results only when switching to the standard PIA calc. 

Also, the console shows two results. The first shows whichever age the slider is set to. The second result shows the default age at 67. 

Will need to spend more time trying to figure out what is going on.

**Comment by thadk** [comment]
Thanks for looking at this, note that the "default" Full Retirement Age (FRA or NRA) is dynamic based on your birth date.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/283343/92311406-ba631a80-ef84-11ea-9835-9a83f65931d0.png">
