### ISSUE TITLE
Month Slider on screen-2 set months to 0 at 70yo but does not revert when changing retirement year

### ISSUE THREAD

**Issue by dmeegan** [codeforboston/windfall-elimination#241]
This issue is related to the new month slider added as part of pull request #230.

See example screencast below:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/57838349/98757713-1be7a100-239b-11eb-8319-6c32a42e7b21.gif)

**Comment by changangus** [comment]
Hey Daniel, 
Could I get assigned this issue? I'd like to take a crack at it.

**Comment by dmeegan** [comment]
> Hey Daniel, 
> 
> Could I get assigned this issue? I'd like to take a crack at it. 

For sure, I will do that now.
