### ISSUE TITLE
Prescreen 1a has typo yearsold when calculating for birthdate before 1955

### ISSUE THREAD

**Issue by dmeegan** [codeforboston/windfall-elimination#242]
The condition rendering is not working for birthdates before 1955. Renders incorrectly as "yearsold"

Changing line 140 in prescreen-1a from` : ""}{" "}` to `: " "}` will fix the issue

See screencast below.
![Pre-Screen 1a _ Windfall Awareness](https://user-images.githubusercontent.com/57838349/98762268-43dc0200-23a5-11eb-9f30-42293d4e65ae.gif)

**Comment by ArunSharmaLearning** [comment]
Can i work on it?

**Comment by thadk** [comment]
@ArunSharmaLearning sure –  welcome to submit a PR.

**Comment by ArunSharmaLearning** [comment]
how can i see the source code?

**Comment by thadk** [comment]
@ArunSharmaLearning please clone the repository and see the "Launching Gatsby Site" section of the readme for setup instructions: https://github.com/codeforboston/windfall-elimination
You will need nodejs installed.

The file for this is in `src/pages/prescreen-1a.tsx` I believe.
