### ISSUE TITLE
Pages need to be able to handle different resolutions

### ISSUE THREAD

**Issue by pnaduthota** [codeforboston/windfall-elimination#52]
This include:
- Site title
- Progress tracker
- footer
- buttons

**Comment by thadk** [comment]
Cane you please specify how you had this in mind so we can work toward it.

**Comment by thadk** [comment]
Hi @prayuthnaduthota, Can you please specify how you had this in mind for each so we can work toward it or comment.

**Comment by rmorantes** [comment]
The current UI looks very stretched out at wider resolutions:

![Screen Shot 2020-03-06 at 7 55 40 AM](https://user-images.githubusercontent.com/22875979/76085728-9cd6d900-5f80-11ea-9b9c-f71cab03e118.png)

And is clipped at narrower resolutions:

![Screen Shot 2020-03-06 at 8 08 13 AM](https://user-images.githubusercontent.com/22875979/76086347-eecc2e80-5f81-11ea-9052-93e9c5cd560b.png)

I'm currently working on adding responsiveness to the header ("About" and "FAQ" links can be moved to the mobile menu):

![ezgif com-optimize](https://user-images.githubusercontent.com/22875979/76097611-02819000-5f96-11ea-933d-5ce2cc4f152b.gif)

IMO, the current sticky footer approach (which I tweaked in #179) works for mobile and tablet resolutions, but for laptop and desktop, embedding the buttons in the content makes more sense.

Giving the content container a max width should fix the stretching issue (also working on): 

![Screen Shot 2020-03-06 at 10 51 01 AM](https://user-images.githubusercontent.com/22875979/76099071-8dfc2080-5f98-11ea-8759-ec4376a6619f.png)

The mobile menu/progress tracker (#155) can be implemented as a separate component that replaces the current progress tracker at mobile resolutions, which I'll turn to next. 

After talking with @markswinimer, to implement the transition between the tablet and mobile mockups (mostly, to collapse the two rightmost columns into one), I'm thinking of using flexbox and something like the following component structure (actual breakpoints to be determined) (on second thought, the green containers might not be needed, will try `flex-wrap: wrap;`):

![Screen Shot 2020-03-06 at 2 35 17 PM](https://user-images.githubusercontent.com/22875979/76116308-c6f7bd80-5fb7-11ea-9786-3d6f59bc4968.png)

![Screen Shot 2020-03-06 at 2 35 27 PM](https://user-images.githubusercontent.com/22875979/76116319-c95a1780-5fb7-11ea-91f3-6d5ff4d7b5c6.png)

![Screen Shot 2020-03-06 at 2 43 00 PM](https://user-images.githubusercontent.com/22875979/76116931-d592a480-5fb8-11ea-9167-cd7bf87069d5.png)

After that, the actual content (form inputs, info blocks, images, warnings, and so on) will need to be tweaked on a page-by-page basis, which should be much easier after the previous bits are implemented. Thoughts? :-)

**Comment by thadk** [comment]
I think we are doing okay on responsive design now.
