### ISSUE TITLE
Pull out the functions from the observable notebook into a module

### ISSUE THREAD

**Issue by adzuci** [codeforboston/windfall-elimination#66]
We have been having issues with contributors running `gatsby develop` and would like to be able to remove the notebook dependency from the gatsby app.

```
success run page queries - 0.068 s — 14/14 405.90 queries/second

 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (246:13)

File: node_modules/windfall-awareness-notebook-prototype/windfall-awareness-notebook-prototype.js:246:13
```

This will involve implementing the UI elements (sliders, date dropdown etc).

![image](https://user-images.githubusercontent.com/278814/63398277-10c1e300-c39b-11e9-9fec-3254a82a58b4.png)

**Comment by thadk** [comment]
Thanks @sw9! I thought it was those lines causing problems but it didn't seem to fix it when I tried.

Also Nick has put together a freestanding javascript file of all the relevant functions to do the calculations based on tables: 
https://github.com/nvanwitt/windfall-elimination/commit/caa019cf5e01f2617e5318b24cfe4af854f595cd

**Comment by sw9** [comment]
I think this issue can be closed
