### ISSUE TITLE
Add Sebastian's lump sum pension option into the calculator

### ISSUE THREAD

**Issue by annemeeker** [codeforboston/windfall-elimination#67]
On the input your pension (noncovered pension) screen, we need to have an option that helps people figure out what to do if they have a lump sum pension instead of a monthly pension.

We will need to ask people if they have a lump sum or a monthly pension. If a monthly pension, they enter the amount, and we're good.

If a lump sum, we need to ask for the amount AND the age when they are eligible to start withdrawing from the lump sum.
To calculate a monthly amount from the lump sum, they look at the table below at the year they become eligible, and divide the lump sum by the number of months the SSA expects them to live.
https://secure.ssa.gov/apps10/poms.nsf/lnx/0300605364

**Comment by supjohn** [comment]
I have created the functions for lump sum pension calculation in https://observablehq.com/d/b133f94d7388d220. It remains to integrate these functions into the rest of the project.

**Comment by thadk** [comment]
Hi @alexjcode – here is the issue we were talking about today. @supjohn let us know if there is anything further to know. 

https://windfall-develop.netlify.com/ is the live version of the `develop` branch

**Comment by annemeeker** [comment]
@alexjcode and @supjohn I just realized looking at the formula for the lump sum calculation that we need to ask users what date they become eligible to start withdrawing from the lump sum without penalty. Could we add that as another user question in the section on the pension?
https://secure.ssa.gov/apps10/poms.nsf/lnx/0300605364

**Comment by alexjcode** [comment]
@annemeeker Yes, that can be added. Would this affect the calculation, or is it separate?

**Comment by alexjcode** [comment]
This integration should be complete soon. There may be an issue with @supjohn 's formula, and I would like to check on that here, so it can be updated:

According to the SSA page linked above, getting the `actuarialValue` number requires inputing the `worker's age` at the time the pension was awarded. The formula right now checks the actuarialMap table using `dateAwarded.year()`, which results in an error, since it's just the year, and not the age.

I'm going to replace it with the worker's age on the `dateAwarded`. Hopefully this will fix the issue

**Comment by alexjcode** [comment]
That part appears to be fixed. I named the resulting variable `ageAwarded`

**Comment by alexjcode** [comment]
Updated the `monthlyPension` formula, so that only the `result` number is being used from the `actuarialValue` object

```js
function lumpSumToMonthly(lumpSum, dateAwarded, workerAge, dob){
  let ageAwarded = dateAwarded.diff(dob, "year")
  let actuarialValue = getActuarialValue(dateAwarded, workerAge, ageAwarded);
  let monthlyPension = Math.floor(lumpSum*100 / actuarialValue.result)/100.00;
  // console.log('actuarialValue', actuarialValue)
  // console.log('monthlyPension', monthlyPension)
  return ({...actuarialValue, monthlyPension});
}
```
