### ISSUE TITLE
Make year62 respect the month of birth

### ISSUE THREAD

**Issue by thadk** [codeforboston/windfall-elimination#95]
As discussed @sw9

**Comment by thadk** [comment]
Maybe as in other places in code:
` import dayjs from "dayjs"; `
` const yearOf62yo = dayjs(dob).add(62, 'years').year()`

**Comment by sw9** [comment]
I looked into this issue more, and it appears that year62 is being calculated properly. I looked at the original observable notebook and the getAIMEFromEarnings uses the whole year value. In places of the code that use fractional years, for example, floatYearsAfter62yo, this is calculated from the dob directly.
